services:
  postgres:
    image: postgres:15-alpine
    container_name: fintech-postgres
    environment:
      POSTGRES_DB: fintech_psp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fintech-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fintech-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - fintech-network

  redis:
    image: redis:7-alpine
    container_name: fintech-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - fintech-network

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  fintech-network:
    driver: bridge
